version: "3.3"
services:
  novella_cms:
    build: .
    container_name: novella_cms
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.novella_cms.rule=Host(`novellacms.com`, `www.novellacms.com`)"
      - "traefik.http.routers.novella_cms.service=novella_cms"
      - "traefik.http.services.novella_cms.loadbalancer.server.port=3000"
    networks:
      - traefik_network

networks:
    traefik_network:
      external: true

